# Generated by Django 3.0.3 on 2020-11-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201127_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiner',
            name='room',
        ),
        migrations.RemoveField(
            model_name='creatormessages',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='joinermessages',
            name='joiner',
        ),
        migrations.AddField(
            model_name='creatormessages',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.AddField(
            model_name='joinermessages',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Joiner',
        ),
    ]
