# Generated by Django 3.0.3 on 2020-12-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201129_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormessages',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='creatormessages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.AlterField(
            model_name='joinermessages',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='joinermessages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
    ]
