# Generated by Django 3.1.3 on 2020-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201203_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='has_left',
            new_name='creator_left',
        ),
        migrations.RemoveField(
            model_name='room',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='room',
            name='pair_left',
            field=models.BooleanField(default=False),
        ),
    ]
