# Generated by Django 3.0.3 on 2020-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201205_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
